apiVersion: v1
kind: Service
metadata:
  name: {{ include "dataplug.fullname" . }}
  labels:
    app.kubernetes.io/component: app
    {{- include "dataplug.labels" . | nindent 4 }}
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}      
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: app
    {{- include "dataplug.selectorLabels" . | nindent 4 }}
