name: Build Facebook plug

on:
  push:
    tags:
      - "facebook-v**"
    branches:
      - "**"
    paths:
      - "dataplug/**"
      - "build.sbt"
      - "dataplug-facebook/**"
      - ".github/workflows/facebook.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache - GHA
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier/v1/https
          key: ${{ runner.OS }}-coursier-cache

      - name: Cache - Resolvers
        run: curl https://${{ secrets.ARTIFACTS_CACHE_BUCKET }}/resolvers.sbt --create-dirs -o ~/.sbt/resolvers.sbt

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
          java-package: jdk
          architecture: x64

      - name: Container - Prepare
        run: sbt "project dataplug-facebook" docker:stage

      - name: Container - Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Container - Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Container - Meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: dataswift/dataplug-facebook
          tags: |
            type=semver,pattern=facebook-v{{version}}
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/heads/main') }}
            type=sha,prefix=main-,format=long,enable=${{ startsWith(github.ref, 'refs/heads/main') }}
            type=sha,prefix=dev-,format=long,suffix=-${{ github.run_id }}

      - name: Container - Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_DATASWIFT_USER }}
          password: ${{ secrets.DOCKERHUB_DATASWIFT_PASS }}

      - name: Container - Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: dataplug-facebook/target/docker/stage/
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=ghcr.io/datasiwft/dataplug-facebook:latest

      - name: Slack
        uses: lazy-actions/slatify@master
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: "*${{ github.workflow }}*"
          channel: "ci"
          commit: true
          mention: "here"
          mention_if: "failure"
          token: ${{ secrets.GITHUB_TOKEN }}
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
