name: Trivy

on:
  workflow_dispatch:
  schedule:
    - cron: "30 3 * * *"

env:
  IMAGE: dataswift/dataplug-facebook:latest

jobs:
  trivy-scan:
    name: Trivy Scan
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:     
      - name: Container - Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: $IMAGE
          format: "template"
          exit-code: 1
          ignore-unfixed: true
          template: "@/contrib/sarif.tpl"
          output: "trivy-results.sarif"
          severity: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"

      - name: Container - Scan - Upload results
        uses: github/codeql-action/upload-sarif@v1
        if: ${{ failure() && github.event_name == 'schedule' && github.ref == 'refs/heads/main' }}
        with:
          sarif_file: "trivy-results.sarif"
